config/routes.rb
Rails.application.routes.draw do
 
root 'pages#welcome'
get '/portfolio' => 'pages#portfolio'
get '/contact' => 'pages#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def welcome
end

def portfolio
end

def contact
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JSavage :: Portfolio</title>

  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="header">
    <div id="nav">
  <ul>
    <li><%= link_to "Welcome", root_path %></li>
    <li><%= link_to "Portfolio", portfolio_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>  
    </div>
  <div id="name">Josh Savage</div>
</div>

<%= yield %>


  <div id="footer">
    <div class="button bb"></div>
    <div class="button li"></div>
    <div class="button tw"></div> <br>
    <div class="copy">Copyright 2015 JSavage</div>
  </div>
</div>
</body>
</html>

app/views/pages/contact.html.erb
   <div id="body">
     <div class="viking">Contact me on <span class="pillage"><a href="https://linkedin.com/in/echoveil">LinkedIn</a></span> or check out my <span class="plunder"><a href="https://bitbucket.org/echoveil">Bitbucket.</a></span></div>
  </div>

app/views/pages/portfolio.html.erb
      


<div class="banner">
    <ul>
        <li><div class="app app1"><div class="apptext">The First Rails App.</div></div></li>
        <li><div class="app app2"><div class="apptext">The Second App: Even Appier.</div></div></li>
        <li><div class="app app3"><div class="apptext">Third Time's The Charm.</div></div></li>
    </ul>
</div>


   <script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="http://unslider.com/unslider.min.js"></script>

     <script>
$(function() {
    $('.banner').unslider();
});

$('.banner').unslider({
    speed: 1000,               //  The speed to animate each slide (in milliseconds)
    delay: 5000,              //  The delay between slide animations (in milliseconds)
    complete: function() {},  //  A function that gets called after every slide animation
    keys: true,               //  Enable keyboard (left, right) arrow shortcuts
    dots: true,               //  Display dot navigation
    fluid: false              //  Support responsive design. May break non-responsive designs
});
     </script>    
 

app/views/pages/welcome.html.erb
                
   <div id="body">
   <div class="container">
     <div class="viking clear">Hello. I am a <span class="pillage">viking</span> who makes <span class="plunder">websites.</span></div>

     <div class="button"><%= link_to "View my work", portfolio_path %></div>
     </div>
  </div>
  